### ISSUE TITLE
Extra Features

### ISSUE THREAD

**Issue by cursorweb** [19wintersp/Europa-Highlighter#1]
Here's some extra features to implement
- [x] Do while loops
- [x] Consider changing the `or` and `and` to keywords?
- [x] #2
- [x] Logo (use the favicon one)

**Comment by 19wintersp** [comment]
@cursorweb For the second one, I'm still not sure. For semantics' sake, I'd rather have them as operators. However, if people prefer to have them as fancy colours (or marked up in another format such as **bold**, which is possible), I'll do that.

**Comment by 19wintersp** [comment]
@cursorweb In terms of snippets, I'll probably copy them from some other extensions, unless you wanted to do that yourself

**Comment by cursorweb** [comment]
Sure, I can implement the snippets.

**Comment by 19wintersp** [comment]
Seems finished, closing
