### ISSUE TITLE
Class declaration and in intellisense not needed

### ISSUE THREAD

**Issue by darkdarcool** [19wintersp/Europa-Highlighter#4]
https://github.com/19wintersp/Europa-Highlighter/blob/bd20d713f2961e5d9b2a1603d52573955fdad877/intellisense/snippets.json#L17

Pretty sure you don’t need this as one of the most advertised things about this language is that it doesn’t have classes?

**Comment by 19wintersp** [comment]
Hi @darkdarcool! Thanks for opening an issue! However, if you check, you'll see that that does not create a class definition, but expands to a struct. The usage of "class" is for semantics's sake, and due to the schema.

**Comment by darkdarcool** [comment]
Oh ok, didn’t see that, thanks!
